version: '3.9'

services:
  skinet-client-dev:
    build:
      context: ../
      dockerfile: Client-Dev.Dockerfile
    container_name: skinet-client-dev
    image: skinet-client-dev
    pull_policy: build
    restart: always
    ports:
      - "4300:4200"
