name: skinetClientProd

on:
  workflow_dispatch:
#  push: 
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 10.10.11.101
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          rm: true
          source: "client/dockerProd/docker-compose.yml"
          target: /skinet-client

      - name: Delay for 5s
        run: sleep 5
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Client-Prod.Dockerfile
          push: true
          tags: |
            a2259687814/skinet-client-prod:latest
            a2259687814/skinet-client-prod:${{ github.sha }}
          cache-from: type=registry,ref=a2259687814/skinet-client-prod:buildcache
          cache-to: type=registry,ref=a2259687814/skinet-client-prod:buildcache,mode=max

      - name: Delay for 5s
        run: sleep 5  
        
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 10.10.11.101
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /skinet-client/client/dockerProd/
            docker compose -p skinet-project up -d
